### ISSUE TITLE
2nd Presentation

### ISSUE THREAD

**Issue by corykitchens** [corykitchens/whoniverse#15]
## TODO
1. Create PowerPoint Presentation

## Cory's TODO
1. [x] Deployment 
2. [x] Planet Implementation
3. [ ] User Auth
4. [x] Change State onCollide 

## Erick's TODO
1. [X] Form for Questions purely built on Phaser
2. [X] Input Validation (Can determine if user got answer right)
3. [X] Different Styles of Forms
4. [X] Function that keeps a Score tally. 
5. [X] Increase or decrease Score depending or correctness of question. 
6. [ ] Addition Assets

**Comment by corykitchens** [comment]
@Americkan If you want to start building out your slides. Feel free to do so then send them my way and I'll make my additions.
